name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠️ Refactoring'
    labels:
      - 'refactor'
      - 'cleanup'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## 🌟 Changes in this release:
  $CHANGES

  ## 📣 Contributors:
  $CONTRIBUTORS 🙌

  ## 🚢 Docker Image:
  You can pull the Docker image from GitHub Container Registry:
  - [ghcr.io/${{ github.actor }}/booklore-app:${{ env.image_tag }}](https://ghcr.io/${{ github.actor }}/booklore-app:${{ env.image_tag }})