name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠️ Refactoring'
    labels:
      - 'refactor'
      - 'cleanup'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'
  - title: '🗂️ Other'
    labels:
      - 'other'
      - 'misc'
      - '*'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## 🚀 Features
  $CHANGES_BY_LABEL:feature,enhancement

  ## 🐛 Bug Fixes
  $CHANGES_BY_LABEL:bug,fix

  ## 🛠️ Refactoring
  $CHANGES_BY_LABEL:refactor,cleanup

  ## 📖 Documentation
  $CHANGES_BY_LABEL:docs,documentation

  ## ⚙️ CI/CD
  $CHANGES_BY_LABEL:ci,cd,workflow

  ## 🗂️ Other
  $CHANGES_BY_LABEL:other,misc