name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠️ Refactoring'
    labels:
      - 'refactor'
      - 'cleanup'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'
  - title: '🗂️ Other'
    labels:
      - 'other'
      - 'misc'
      - '*'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## Release Notes:
  
  ### 🚀 Features:
  $FEATURES

  ### 🐛 Bug Fixes:
  $BUGS

  ### 🛠️ Refactoring:
  $REFACTOR

  ### 📖 Documentation:
  $DOCS

  ### ⚙️ CI/CD:
  $CICD

  ### 🗂️ Other:
  $OTHER