name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '✨ Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠️ Refactoring & Maintenance'
    labels:
      - 'refactor'
      - 'cleanup'
      - 'chore'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## 🌟 Changes in this release:
  $CHANGES