app:
  path-config: '/app/data'
  version: 'v0.0.40'

  remote-auth:
    enabled: ${REMOTE_AUTH_ENABLED:false}
    create-new-users: ${REMOTE_AUTH_CREATE_NEW_USERS:true}
    header-name: ${REMOTE_AUTH_HEADER_NAME:Remote-Name}
    header-user: ${REMOTE_AUTH_HEADER_USER:Remote-User}
    header-email: ${REMOTE_AUTH_HEADER_EMAIL:Remote-Email}
    header-groups: ${REMOTE_AUTH_HEADER_GROUPS:Remote-Groups}
    admin-group: ${REMOTE_AUTH_ADMIN_GROUP}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 600000
  application:
    name: booklore-api
  datasource:
    url: ${DATABASE_URL:jdbc:mariadb://${DATABASE_HOST:${DB_HOST:mariadb}}:${DATABASE_PORT:3306}/${DATABASE_NAME:booklore}?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:${MYSQL_ROOT_PASSWORD}}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    com.adityachandel.booklore: ${LOG_LEVEL:INFO}
    org.apache.fontbox: ERROR
    org.apache.pdfbox: ERROR